# docker-compose.yml
version: '3.7'

services:
  mlflow:
    image: mlflow/mlflow
    environment:
      - BACKEND_STORE_URI=sqlite:///mlflow.db
      - ARTIFACT_ROOT=/mlflow/artifacts
      - MLFLOW_TRACKING_URI=http://localhost
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/mlflow
