name: Lint and Format

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install pylint flake8 black

      - name: Lint with pylint
        run: |
          pylint .

      - name: Lint with flake8
        run: |
          flake8 .

      - name: Format code with black
        run: |
          black --check .